baseURL = "https://ctxzz-ai.github.io/til-blog/"
languageCode = "en-us"
title = "TIL Blog"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"
